#! groovy

// Standard job properties
def jobProps = [
  buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '50')),
  disableResume(),
  durabilityHint("PERFORMANCE_OPTIMIZED"),
  [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false]
]

def paramsList = [
    string(name: 'API_Server_URL', defaultValue: "api.", description: 'clustre api server url'),
    string(name: 'API_Server_Port', defaultValue: "6443", description: 'clustrer api serfver port number'),
    string(name: 'cluster_admin', defaultValue: "kubeadmin", description: 'clustrer admin user'),
    password(name: 'cluster_admin_password', description: 'cluster admin password'),
    string(name: 'ocp_client_version', defaultValue: "4.2.0"),
    string(name: 'machine_config', description: 'machine config found from oc get mc, newest version')
  ]
jobProps.push(parameters(paramsList))

properties(jobProps)

timestamps {
  ansiColor('xterm') {
    node ( 'kube_pod_slave' ) {

      //def scmVars = checkout scm
      checkout scm
      stage('Stage 1') {
        echo "This is a test"
        echo "${params.API_Server_URL}"
        echo "${params.API_Server_Port}"
        echo "${params.cluster_admin}"
        echo "${params.cluster_admin_password}"
      }

      stage('Stage 2') {
        sh """
          cp ./ansible/recover-machine-config-play/examples/mc_vars.yml ./ansible/recover-machine-config-play/;cp ./ansible/recover-machine-config-play/examples/inventory ./ansible/recover-machine-config-play/;cat ./ansible/recover-machine-config-play/inventory; ansible-playbook -i ./ansible/recover-machine-config-play/inventory ./ansible/recover-machine-config-play/recover-machine-config-play.yml -e kubeadmin_user=${params.cluster_admin} -e kubeadmin_password=${params.cluster_admin_password} -e ocp_api_url=${API_Server_URL}:${API_Server_Port} -e arch="linux" -e ocp_client_version=${ocp_client_version} -e machine_config=${machine_config} -vv
        """.stripIndent()
      }
   }
  }
}