#! groovy

// Standard job properties
def jobProps = [
  buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '50')),
  disableResume(),
  durabilityHint("PERFORMANCE_OPTIMIZED"),
  [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false]
]

def paramsList = [
    string(name: 'osnames', defaultValue: 'changeMyhostname', description: 'comma delimitted list of IPs or hostnames'),
    string(name: 'external_password_file', defaultValue: '/etc/ansible/nestvars.yml', description: 'location of password yml file'),
    string(name: 'regionTimeZone', defaultValue: 'America/New_York', description: 'set the timezone->https://en.wikipedia.org/wiki/List_of_tz_database_time_zones'),
    string(name: 'authorized_keys_url', defaultValue: '\'\'', description: 'URL location of a file containg id_rsa.pub keys'),
  ]
jobProps.push(parameters(paramsList))

properties(jobProps)

timestamps {
  ansiColor('xterm') {
    node ( 'kube_pod_slave' ) {

      //def scmVars = checkout scm
      checkout scm
      stage('Stage 1') {
        sh """
          set +x # hide sensitive info being echo'd to log
          cp ./ansible/setup-new-fyre-host-play/examples/inventory ./ansible/setup-new-fyre-host-play/; ansible-playbook -i ${params.osnames}, ./ansible/setup-new-fyre-host-play/setup-new-fyre-host-play.yml -e ${params.external_password_file} -e ${params.regionTimeZone} -e ${params.authorized_keys_url}
        """.stripIndent()
      }
   }
  }
}
