#! groovy

// Standard job properties
def jobProps = [
  buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '50')),
  disableResume(),
  durabilityHint("PERFORMANCE_OPTIMIZED"),
  [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false]
]

def paramsList = [
    string(name: 'osnames', defaultValue: 'changeMyhostname', description: 'comma delimitted list of IPs or hostnames'),
    string(name: 'regionTimeZone', defaultValue: 'America/New_York', description: 'set the timezone->https://en.wikipedia.org/wiki/List_of_tz_database_time_zones'),
    string(name: 'authorized_keys_url', defaultValue: '/mnt/data/.load_secrets_dir/nest_infrastructure.keys', description: 'URL or file location of a file containg id_rsa.pub keys'),
    string(name: 'load_secrets_dir', defaultValue: '/mnt/data/.load_secrets_dir', description: 'location secrets'),
    string(name: 'passwordfile', defaultValue: '/mnt/data/.load_secrets_dir/.password', description: 'location secrets'),
  ]
jobProps.push(parameters(paramsList))

properties(jobProps)

timestamps {
  ansiColor('xterm') {
    node ( 'kube_pod_slave' ) {

      //def scmVars = checkout scm
      checkout scm
      stage('Stage 1') {
        sh """
          set +x # hide sensitive info being echo'd to log
	  export ANSIBLE_FORCE_COLOR=true
          cp ./ansible/setup-new-fyre-host-play/examples/inventory ./ansible/setup-new-fyre-host-play/; ansible-playbook -i ${params.osnames}, ./ansible/setup-new-fyre-host-play/setup-new-fyre-host-play.yml -e regionTimeZone=${params.regionTimeZone} -e authorized_keys_url=${params.authorized_keys_url} -e load_secrets_dir=${params.load_secrets_dir} --vault-password-file=${params.passwordfile}
        """.stripIndent()
      }
   }
  }
}
