---
# 1. Get checksum from master host (run once)
- name: Get LTPA checksum from master host
  ansible.builtin.stat:
    path: "{{ ltpa_file_path }}"
    checksum_algorithm: sha256
  register: master_ltpa_stat
  delegate_to: "{{ ltpa_master_host }}"
  run_once: true

- name: Sync ltpa.keys
  when: master_ltpa_stat.stat.exists
  block:

    # 2. Get checksum from each node
    - name: Get LTPA checksum from local host
      ansible.builtin.stat:
        path: "{{ ltpa_file_path }}"
        checksum_algorithm: sha256
      register: local_ltpa_stat

    - name: Sync LTPA keys from master host
      ansible.builtin.synchronize:
        src: "{{ ltpa_file_path }}"
        dest: "{{ ltpa_file_path }}"
        mode: pull
        archive: true
        perms: true
        checksum: true
      vars:
        ansible_ssh_common_args: >
          -o StrictHostKeyChecking=no
      when:
        - inventory_hostname != ltpa_master_host
        - local_ltpa_stat.stat.checksum | default('') != master_ltpa_stat.stat.checksum
