FROM ubuntu
USER root
RUN apt -y update && \
    apt -y install python3 python3-pip git curl wget sudo jq gpg vim sshpass && \ 
    pip3 install --upgrade pip && \ 
    pip3 install ansible 
COPY community-automation/ community-automation
RUN ansible-galaxy collection install -r community-automation/ansible/prereq-play/requirements.yml && \
    ansible-playbook -i community-automation/ansible/prereq-play/inventory community-automation/ansible/prereq-play/prereq-play.yml && \
    rm -rf community-automation
ENTRYPOINT [ "/bin/bash" ]
WORKDIR /community-automation/ansible 

