---
- name: Check for the existence ltpa.keys
  ansible.bulitin.stat:
    path: /tmp/ltpa.keys
  register: onprem

- name: Put ltpa.keys
  when: onprem.stat.exists
  block:
    - name: Copy the ltpa.keys
      ansible.builtin.copy:
        src: /tmp/ltpa.keys
        dest: "{{ wlp_usr_dir }}/servers/{{ wl_server }}/resources/security/ltpa.keys"
        mode: '0755'
