#! groovy

// Standard job properties
def jobProps = [
  buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '50')),
  disableResume(),
  durabilityHint("PERFORMANCE_OPTIMIZED"),
  [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false]
]

def paramsList = [
    string(name: 'stackName', defaultValue: 'changeMyStackName', description: 'name of fyre stack'),
    string(name: 'jmeterUser', defaultValue: 'changeMyjmeterUser', description: 'name of non-root user ( Do not use jmeter )'),
    string(name: 'fyreuser', description: 'username for accessing fyre api'),
    password(name: 'fyreapikey', description: 'fyre api key'),
    string(name: 'javaArchive', defaultValue: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10+9_openj9-0.24.0/OpenJDK11U-jdk_x64_linux_openj9_linuxXL_11.0.10_9_openj9-0.24.0.tar.gz',description: 'url of source java archive'),
    string(name: 'jmeterArchive', defaultValue: 'http://www.gtlib.gatech.edu/pub/apache/jmeter/binaries/apache-jmeter-5.4.1.tgz', description: 'url of source jmeter archive'),
    string(name: 'jmeterManagerPluginUrl', defaultValue: 'https://jmeter-plugins.org/get/'),
    booleanParam(name: 'enableVNC', defaultValue: false, description: 'configure VNC Server on jmeter host'),
  ]
jobProps.push(parameters(paramsList))

properties(jobProps)

timestamps {
  ansiColor('xterm') {
    node {

      //def scmVars = checkout scm
      checkout scm
      stage('Stage 1') {
        sh """
          set +x # hide sensitive info being echo'd to log
	  export ANSIBLE_FORCE_COLOR=true
          cp ./ansible/request-rhel-jmeter-fyre-play/examples/inventory ./ansible/request-rhel-jmeter-fyre-play/; ansible-playbook -i ./ansible/request-rhel-jmeter-fyre-play/inventory ./ansible/request-rhel-jmeter-fyre-play/request-rhel-jmeter-fyre-play.yml -e fyreuser=${params.fyreuser} -e fyreapikey=${params.fyreapikey} -e vnc=${params.enableVNC} -e jmeterUser=${params.jmeterUser} -e noLog=false -e javaArchive=${params.javaArchive}  -e jmeterArchive=${params.jmeterArchive} -e jmeterManagerPluginUrl=${params.jmeterManagerPluginUrl} -e stackName=${params.stackName}
        """.stripIndent()
      }
   }
  }
}
