#! groovy

// Standard job properties
def jobProps = [
  buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '50')),
  disableResume(),
  durabilityHint("PERFORMANCE_OPTIMIZED"),
  [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false]
]

def paramsList = [
    string(name: 'stackName', defaultValue: 'changeMyStackName', description: 'name of fyre stack'),
    string(name: 'fyreuser', description: 'username for accessing fyre api'),
    password(name: 'fyreapikey', description: 'fyre api key'),
    string(name: 'crcarchive', defaultValue: 'http://svt-auto01.fyre.ibm.com/opt/crc-linux-amd64.tar.xz', description: 'url of source crc xz'),
    booleanParam(name: 'enableVNC', defaultValue: false, description: 'configure VNC Server on crc host')
  ]
jobProps.push(parameters(paramsList))

properties(jobProps)

timestamps {
  ansiColor('xterm') {
    node {

      //def scmVars = checkout scm
      checkout scm
      stage('Stage 1') {
        sh """
          set +x # hide sensitive info being echo'd to log
          cp ./ansible/request-crc-fyre-play/examples/inventory ./ansible/request-crc-fyre-play/; ansible-playbook -i ./ansible/request-crc-fyre-play/inventory ./ansible/request-crc-fyre-play/request-crc-fyre-play.yml -e fyreuser=${params.fyreuser} -e fyreapikey=${params.fyreapikey} -e vnc=${params.enableVNC} -e stackName=${params.stackName} -e noLog=false -e crc_download_src=${params.crcarchive} --vault-password-file ./ansible/roles/crc_start/files/crc_pull_pass 
        """.stripIndent()
      }
   }
  }
}
