---
# specific OS supports wildcards
- name: remove extraneous packages
  become: true
  ansible.builtin.package:
   name: "{{ packages }}"
   state: absent
  vars:
   packages:
   - "adobe*"
   - "java*"
   - "samba*"
   - "valgrind*"
   - "tignervnc"
  register: zypper_remove_result
  failed_when: false
  changed_when: zypper_remove_result.changed | default(false)

- name: zypper update
  become: true
  ansible.builtin.package:
   name: '*'
   state: latest

- name: install packages
  become: true
  ansible.builtin.package:
   name: "{{ packages }}"
   state: present
  vars:
   packages:
   - 'xorg-x11-xauth'
   - 'less'
   - 'zip'
   - 'unzip'

