---
# specific OS supports wildcards
- name: Remove extraneous packages
  become: true
  ansible.builtin.package:
   name: "{{ packages }}"
   state: absent
  vars:
    packages:
      - "adobe*"
      - "java*"
      - "samba*"
      - "valgrind*"
      - "tignervnc"
  register: zypper_remove_result
  failed_when: false
  changed_when: zypper_remove_result.changed | default(false)

- name: Zypper update
  become: true
  ansible.builtin.package:
   name: '*'
   state: latest

- name: Install packages
  become: true
  ansible.builtin.package:
   name: "{{ packages }}"
   state: present
  vars:
   packages:
    - 'xorg-x11-xauth'
    - 'less'
    - 'psmisc'
    - 'bind-utils'
    - 'insserv-compat'
    - 'zip'
    - 'unzip'
