---
# specific OS supports wildcards
- name: Remove extraneous packages
  become: true
  ansible.builtin.apt:
   name: "{{ packages }}"
   state: absent
   autoremove: true
  vars:
    packages:
    - "java*"
    - "samba*"
    - "valgrind*"
    - "tignervnc"
    - 'tigervnc-standalone-server'
    - 'xorg-x11-fonts-Type1'
  register: apt_remove_result
  failed_when: false
  changed_when: apt_remove_result.changed | default(false)

- name: Apt update
  become: true
  ansible.builtin.apt:
    name: '*'
    state: latest

- name: Install packages
  become: true
  ansible.builtin.apt:
   name: "{{ packages }}"
   state: present
  vars:
    packages:
    - 'libxtst6'
    - 'libgtk2.0-0'
    - 'libxft2'
    - 'zip'
    - 'unzip'
