#! groovy

// Standard job properties
def jobProps = [
  buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '50')),
  disableResume(),
  durabilityHint("PERFORMANCE_OPTIMIZED"),
  [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false]
]

def paramsList = [
    string(name: 'osnames', defaultValue: 'changeMyhostname', description: 'comma delimitted list of IPs or hostnames'),
    password(name: 'load_secrets_dir', defaultValue: '/mnt/data/.load_secrets_dir', description: 'location secrets'),
    password(name: 'passwordfile', defaultValue: '/mnt/data/.load_secrets_dir/.password', description: 'location secrets'),
  ]
jobProps.push(parameters(paramsList))

properties(jobProps)

timestamps {
  ansiColor('xterm') {
    node {

      //def scmVars = checkout scm
      checkout scm
      stage('Stage 1') {
        sh """
          set +x # hide sensitive info being echo'd to log
          cp ./ansible/nest-user-play/examples/inventory ./ansible/nest-user-play/; ansible-playbook -i ${params.osnames}, ./ansible/nest-user-play/nest-user-play.yml  -e load_secrets_dir=$load_secrets_dir --vault-password-file ${params.$passwordfile} 
        """.stripIndent()
      }
   }
  }
}
